const data = [
  {
    id: 0,
    name: "Alicia Wright",
    img: "images/2.jpg",
    msg: "Ok. Let's meet with the client tomorrow.",
    time: "10:34 AM",
    job: "Product Manager",
  },
  {
    id: 1,
    name: "Joe Lutz",
    img: "images/3.jpg",
    msg: "Nice to meet you.",
    time: "10:28 AM",
    job: "Database Administrator",
  },
  {
    id: 2,
    name: "Kendall Campbell",
    img: "images/4.jpg",
    msg: "That's great! then start working from tomorrow.",
    time: "09:14 AM",
    job: "Senior Manager",
  },
  {
    id: 3,
    name: "Amanda Rushing",
    img: "images/5.jpg",
    msg: "First of all, let's meet with the company CEO.",
    time: "08:30 AM",
    job: "Fullstack Developer",
  },
  {
    id: 4,
    name: "Trina George",
    img: "images/6.jpg",
    msg: "That sounds good!",
    time: "08:34 AM",
    job: "React Developer",
  },
  {
    id: 5,
    name: "Edward Wesley",
    img: "images/7.jpg",
    msg: "The component will be ready by tomorrow.",
    time: "07:12 AM",
    job: "Blockchain Developer",
  },
  {
    id: 5,
    name: "Rachana Iyer",
    img: "images/8.jpg",
    msg: "I have already deployed the modules.",
    time: "06:44 AM",
    job: "Network Analyst",
  },
];

export default data;
